### ISSUE TITLE
提轴器脚本输出无效

### ISSUE THREAD

**Issue by SatenRuiko10032** [Gibberer/pcr-script#12]
你好大佬，我这启用脚本后没有任何输出。目录自建输出文件output.yaml，也没有输出
![JJZU1Z4J4UY80UNV1 XZWKE](https://user-images.githubusercontent.com/129540301/229185987-afd49e61-7b8a-443d-a5ba-67c2cc6ca90d.png)

**Comment by AlphaBoom** [comment]
你好，如果有问题的话应该会有错误日志出现的，所以是生成了一个空的output.yaml?
我跑了下这个脚本，现在是会报错，原因是新版本paddleocr返回的数据结构发生了变化，需要把[这里](https://github.com/Gibberer/pcr-script/blob/master/plugins/battleline_extractor/battleline_parser.py#L33)改成ret[0]才能正常执行。不过这可能和你遇到的问题无关，也可以在这块打印下paddleocr的返回结果看看。

**Comment by SatenRuiko10032** [comment]
我纯是菜鸟。这边执行后并没有生产空的output.yaml
尝试把 for line in ret:改成ret[0] 会报错unexpected indent。或者改成 for line in ret[0]: 返回的结果跟一开始一样。
我这里看了一下我的paddleocr版本是 2.6.1.3 
paddlepaddle-gpu      0.0.0.post102

**Comment by SatenRuiko10032** [comment]
你好，我尝试降低paddleocr版本为2.5.0.3，paddlepaddle 换成CPU2.3.0后调试。出现了这样的情况。
![_`3 D%~$B1}%8YCMBSP{J}Y](https://user-images.githubusercontent.com/129540301/229310310-5049902f-17d3-4d7c-bc5f-0881e38fd10f.png)

[2023/04/02 03:17:12] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, image_dir=None, det_algorithm='DB', det_model_dir='C:\\Users\\UserSS/.paddleocr/whl\\det\\ch\\ch_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_box_type='quad', det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, det_fce_box_type='poly', rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\UserSS/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv3_rec_infer', rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='F:\\Program Files\\Python39\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='C:\\Users\\UserSS/.paddleocr/whl\\cls\\ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_model_dir=None, table_char_dict_path=None, layout_path_model='lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config', layout_label_map=None, mode='structure', layout=True, table=True, ocr=True, lang='ch', det=True, rec=True, type='ocr', ocr_version='PP-OCRv3', structure_version='PP-STRUCTURE')
Traceback (most recent call last):
  File "C:\Users\UserSS\Desktop\333\pcr-script-master\plugins\battleline_extractor\battleline_extractor.py", line 7, in <module>
    result = parser.parse(cv.imread("test.png"))
  File "C:\Users\UserSS\Desktop\333\pcr-script-master\plugins\battleline_extractor\battleline_parser.py", line 62, in parse
    grouped_rec = self._ocr(image)
  File "C:\Users\UserSS\Desktop\333\pcr-script-master\plugins\battleline_extractor\battleline_parser.py", line 69, in _ocr
    rec_ret = self._recognizer.recognize(image)
  File "C:\Users\UserSS\Desktop\333\pcr-script-master\plugins\battleline_extractor\battleline_parser.py", line 30, in recognize
    ret = self._paddle_ocr.ocr(image, cls=True)
  File "F:\Program Files\Python39\lib\site-packages\paddleocr\paddleocr.py", line 474, in ocr
    dt_boxes, rec_res = self.__call__(img, cls)
  File "F:\Program Files\Python39\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 69, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "F:\Program Files\Python39\lib\site-packages\paddleocr\tools\infer\predict_det.py", line 242, in __call__
    post_result = self.postprocess_op(preds, shape_list)
  File "F:\Program Files\Python39\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 188, in __call__
    boxes, scores = self.boxes_from_bitmap(pred[batch_index], mask,
  File "F:\Program Files\Python39\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 82, in boxes_from_bitmap
    score = self.box_score_fast(pred, points.reshape(-1, 2))
  File "F:\Program Files\Python39\lib\site-packages\paddleocr\ppocr\postprocess\db_postprocess.py", line 140, in box_score_fast
    xmin = np.clip(np.floor(box[:, 0].min()).astype(np.int), 0, w - 1)
  File "F:\Program Files\Python39\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by AlphaBoom** [comment]
你不需要回退版本使用最新的就好，我上边测试是paddleocr和paddlepaddle都是最新版本的。
你可以打印下paddleocr的返回值,如下操作：
```python
    def recognize(self, image:ndarray)->Iterable[RecResult]:
        ret = self._paddle_ocr.ocr(image, cls=True)
        print(ret) # 打印一下paddleocr的返回结果
        if ret:
            result = []
            for line in ret:
                result.append(RecResult(bounds=line[0], content = line[1][0], accuracy = line[1][1]))
            return result
        else:
            return None
```
另外确认下使用的图片是项目里带的那张测试[图片](https://github.com/Gibberer/pcr-script/blob/master/plugins/battleline_extractor/test.png)么？希望我们的环境没有过多的差异。

**Comment by SatenRuiko10032** [comment]
好了。感谢大佬。更换最新版本的paddleocr和paddlepaddle（用的先行版。稳定版各种环境不冲突），再修改py脚本后正常输出文字了。感谢
